functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары  
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины  
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:  
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Корзина будет хранится в сессии браузера
  - Нужна адаптивная верстка, чтобы сайт был удобным на мобильных устройствах
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  
